#!/usr/bin/env sh
# scripts/map.sh
# Regenerates docs/MAP.md from the tracked file list, only when that list
# changed. Zero LLM. Called by the pre-commit hook, or by hand.
#
# Install the hook once:
#   ln -sf ../../scripts/map.sh .git/hooks/pre-commit
# Force a rebuild:
#   scripts/map.sh --force

set -eu

OUT="docs/MAP.md"
HASH_FILE=".git/map.hash"
DEPTH="${MAP_DEPTH:-3}"
# Agent configuration folders are excluded: the map is for finding project code,
# and every target installs the same workflow under a different dotted name.
EXCLUDE='^(docs/archive/|\.(kilo|kilocode|claude|opencode|cursor|agents|github)/)'

cd "$(git rev-parse --show-toplevel)"

# Own temp file, removed on any exit. A fixed /tmp path is shared by every
# repository on the machine and by every concurrent commit in this one.
PATHS="$(mktemp "${TMPDIR:-/tmp}/map.paths.XXXXXX")"
trap 'rm -f "$PATHS"' EXIT HUP INT TERM

# Tracked files plus staged additions, minus staged deletions. That is what
# the commit will contain, so the map matches the commit, not the previous one.
files="$(git ls-files --cached | grep -Ev "$EXCLUDE" | grep -vx "$OUT" | sort -u)"
hash="$(printf '%s' "$files" | git hash-object --stdin)"

if [ "${1:-}" != "--force" ] && [ -f "$HASH_FILE" ] && [ "$(cat "$HASH_FILE")" = "$hash" ]; then
  exit 0
fi

# Collapse to directories up to DEPTH, keep files at the last level.
# Awk builds the tree from paths, so no dependency on `tree` being installed.
printf '%s\n' "$files" | awk -v depth="$DEPTH" '
{
  n = split($0, p, "/")
  path = ""
  for (i = 1; i <= n && i <= depth; i++) {
    path = (path == "" ? p[i] : path "/" p[i])
    if (i < n && i == depth) { dirs[path "/"]++; break }
    if (i < n) { seen[path "/"] = 1 } else { seen[path] = 1 }
  }
}
END {
  for (k in dirs) seen[k] = 1
  for (k in seen) print k
}' | sort > "$PATHS"

{
  echo "# Map"
  echo
  echo "Generated by scripts/map.sh from git ls-files. Do not edit."
  echo "Depth: $DEPTH. Folders ending in / are collapsed. Meaning of each"
  echo "top-level folder lives in docs/CONTEXT.md under Layout."
  echo
  echo '```'
  awk '{
    n = split($0, p, "/")
    isdir = ($0 ~ /\/$/)
    lvl = isdir ? n - 2 : n - 1
    indent = ""
    for (i = 0; i < lvl; i++) indent = indent "  "
    name = isdir ? p[n-1] "/" : p[n]
    print indent name
  }' "$PATHS"
  echo '```'
  echo
  echo "Tracked files: $(printf '%s\n' "$files" | wc -l | tr -d ' ')"
} > "$OUT"

printf '%s' "$hash" > "$HASH_FILE"
git add "$OUT"
echo "map: $OUT regenerated"
